apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyhttpd01.fullname" . }}
  labels:
    {{- include "pyhttpd01.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "pyhttpd01.selectorLabels" . | nindent 4 }}
